version: '3.8'

services:
  postgres:
    image: postgres:13.2-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SSLMODE: disable
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 2s
      retries: 5

  # app builds and runs the binary for acceptance/back-box tests
  app:
    build:
      context: .
      dockerfile: ./cmd/rpmserver/Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
      - ${GRPC_PORT}:${GRPC_PORT}
    working_dir: /app
    env_file:
      - .env
    environment:
      WORKDIR: /app
      POSTGRES_HOST: postgres
      POSTGRES_READ_REPLICA_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SSLMODE: disable
      SERVICE_CERT_FILE: /app/service.pem
      SERVICE_KEY_FILE: /app/service.key
    depends_on:
      postgres:
        condition: service_healthy