version: '3.9'

services:
  postgres:
    image: postgres:13.2-alpine
    container_name: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: rpm
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rpm
      POSTGRES_SSLMODE: disable
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  appci:
    image: golang:1.19-alpine
    ports:
      - "80"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      WORKDIR: /app
      POSTGRES_HOST: postgres
      POSTGRES_READ_REPLICA_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: rpm
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rpm
      POSTGRES_SSLMODE: disable
    depends_on:
      postgres:
        condition: service_healthy
