// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: rpm.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Property struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropertyID string `protobuf:"bytes,1,opt,name=propertyID,proto3" json:"propertyID,omitempty"`
	Street     string `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	City       string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State      string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Zip        string `protobuf:"bytes,5,opt,name=zip,proto3" json:"zip,omitempty"`
}

func (x *Property) Reset() {
	*x = Property{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_rpm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_rpm_proto_rawDescGZIP(), []int{0}
}

func (x *Property) GetPropertyID() string {
	if x != nil {
		return x.PropertyID
	}
	return ""
}

func (x *Property) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Property) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Property) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Property) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

type StorePropertyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropertyID string `protobuf:"bytes,1,opt,name=propertyID,proto3" json:"propertyID,omitempty"` // uuid generated when omitted
	Street     string `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	City       string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State      string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Zip        string `protobuf:"bytes,5,opt,name=zip,proto3" json:"zip,omitempty"`
}

func (x *StorePropertyReq) Reset() {
	*x = StorePropertyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorePropertyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorePropertyReq) ProtoMessage() {}

func (x *StorePropertyReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorePropertyReq.ProtoReflect.Descriptor instead.
func (*StorePropertyReq) Descriptor() ([]byte, []int) {
	return file_rpm_proto_rawDescGZIP(), []int{1}
}

func (x *StorePropertyReq) GetPropertyID() string {
	if x != nil {
		return x.PropertyID
	}
	return ""
}

func (x *StorePropertyReq) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *StorePropertyReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *StorePropertyReq) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StorePropertyReq) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

type StorePropertyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropertyID string `protobuf:"bytes,1,opt,name=propertyID,proto3" json:"propertyID,omitempty"`
}

func (x *StorePropertyRes) Reset() {
	*x = StorePropertyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorePropertyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorePropertyRes) ProtoMessage() {}

func (x *StorePropertyRes) ProtoReflect() protoreflect.Message {
	mi := &file_rpm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorePropertyRes.ProtoReflect.Descriptor instead.
func (*StorePropertyRes) Descriptor() ([]byte, []int) {
	return file_rpm_proto_rawDescGZIP(), []int{2}
}

func (x *StorePropertyRes) GetPropertyID() string {
	if x != nil {
		return x.PropertyID
	}
	return ""
}

type GetPropertyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropertyID string `protobuf:"bytes,1,opt,name=propertyID,proto3" json:"propertyID,omitempty"`
}

func (x *GetPropertyReq) Reset() {
	*x = GetPropertyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPropertyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPropertyReq) ProtoMessage() {}

func (x *GetPropertyReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPropertyReq.ProtoReflect.Descriptor instead.
func (*GetPropertyReq) Descriptor() ([]byte, []int) {
	return file_rpm_proto_rawDescGZIP(), []int{3}
}

func (x *GetPropertyReq) GetPropertyID() string {
	if x != nil {
		return x.PropertyID
	}
	return ""
}

type GetPropertyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Property *Property `protobuf:"bytes,1,opt,name=property,proto3" json:"property,omitempty"`
}

func (x *GetPropertyRes) Reset() {
	*x = GetPropertyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPropertyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPropertyRes) ProtoMessage() {}

func (x *GetPropertyRes) ProtoReflect() protoreflect.Message {
	mi := &file_rpm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPropertyRes.ProtoReflect.Descriptor instead.
func (*GetPropertyRes) Descriptor() ([]byte, []int) {
	return file_rpm_proto_rawDescGZIP(), []int{4}
}

func (x *GetPropertyRes) GetProperty() *Property {
	if x != nil {
		return x.Property
	}
	return nil
}

type RemovePropertyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropertyID string `protobuf:"bytes,1,opt,name=propertyID,proto3" json:"propertyID,omitempty"`
}

func (x *RemovePropertyReq) Reset() {
	*x = RemovePropertyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovePropertyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePropertyReq) ProtoMessage() {}

func (x *RemovePropertyReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePropertyReq.ProtoReflect.Descriptor instead.
func (*RemovePropertyReq) Descriptor() ([]byte, []int) {
	return file_rpm_proto_rawDescGZIP(), []int{5}
}

func (x *RemovePropertyReq) GetPropertyID() string {
	if x != nil {
		return x.PropertyID
	}
	return ""
}

type RemovePropertyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemovePropertyRes) Reset() {
	*x = RemovePropertyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovePropertyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePropertyRes) ProtoMessage() {}

func (x *RemovePropertyRes) ProtoReflect() protoreflect.Message {
	mi := &file_rpm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePropertyRes.ProtoReflect.Descriptor instead.
func (*RemovePropertyRes) Descriptor() ([]byte, []int) {
	return file_rpm_proto_rawDescGZIP(), []int{6}
}

type PropertyFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PropertyFilter) Reset() {
	*x = PropertyFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpm_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PropertyFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyFilter) ProtoMessage() {}

func (x *PropertyFilter) ProtoReflect() protoreflect.Message {
	mi := &file_rpm_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyFilter.ProtoReflect.Descriptor instead.
func (*PropertyFilter) Descriptor() ([]byte, []int) {
	return file_rpm_proto_rawDescGZIP(), []int{7}
}

var File_rpm_proto protoreflect.FileDescriptor

var file_rpm_proto_rawDesc = []byte{
	0x0a, 0x09, 0x72, 0x70, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x72, 0x70, 0x6d,
	0x70, 0x62, 0x22, 0x7e, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x12, 0x1e,
	0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x49, 0x44, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x7a, 0x69, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x7a,
	0x69, 0x70, 0x22, 0x86, 0x01, 0x0a, 0x10, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x79, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x7a, 0x69, 0x70,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x7a, 0x69, 0x70, 0x22, 0x32, 0x0a, 0x10, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x73, 0x12,
	0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x49, 0x44, 0x22,
	0x30, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x49,
	0x44, 0x22, 0x3d, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79,
	0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x72, 0x70, 0x6d, 0x70, 0x62, 0x2e, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79,
	0x22, 0x33, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x79, 0x49, 0x44, 0x22, 0x13, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x32, 0x87, 0x02, 0x0a,
	0x03, 0x52, 0x50, 0x4d, 0x12, 0x41, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x79, 0x12, 0x17, 0x2e, 0x72, 0x70, 0x6d, 0x70, 0x62, 0x2e, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x17,
	0x2e, 0x72, 0x70, 0x6d, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x73, 0x12, 0x3b, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x12, 0x15, 0x2e, 0x72, 0x70, 0x6d, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e,
	0x72, 0x70, 0x6d, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x79, 0x52, 0x65, 0x73, 0x12, 0x44, 0x0a, 0x0e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x12, 0x18, 0x2e, 0x72, 0x70, 0x6d, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x71,
	0x1a, 0x18, 0x2e, 0x72, 0x70, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x0e, 0x4c, 0x69,
	0x73, 0x74, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x72,
	0x70, 0x6d, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x1a, 0x0f, 0x2e, 0x72, 0x70, 0x6d, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x79, 0x30, 0x01, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x63, 0x6b, 0x65, 0x2f, 0x72, 0x70, 0x6d,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_rpm_proto_rawDescOnce sync.Once
	file_rpm_proto_rawDescData = file_rpm_proto_rawDesc
)

func file_rpm_proto_rawDescGZIP() []byte {
	file_rpm_proto_rawDescOnce.Do(func() {
		file_rpm_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpm_proto_rawDescData)
	})
	return file_rpm_proto_rawDescData
}

var file_rpm_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rpm_proto_goTypes = []interface{}{
	(*Property)(nil),          // 0: rpmpb.Property
	(*StorePropertyReq)(nil),  // 1: rpmpb.StorePropertyReq
	(*StorePropertyRes)(nil),  // 2: rpmpb.StorePropertyRes
	(*GetPropertyReq)(nil),    // 3: rpmpb.GetPropertyReq
	(*GetPropertyRes)(nil),    // 4: rpmpb.GetPropertyRes
	(*RemovePropertyReq)(nil), // 5: rpmpb.RemovePropertyReq
	(*RemovePropertyRes)(nil), // 6: rpmpb.RemovePropertyRes
	(*PropertyFilter)(nil),    // 7: rpmpb.PropertyFilter
}
var file_rpm_proto_depIdxs = []int32{
	0, // 0: rpmpb.GetPropertyRes.property:type_name -> rpmpb.Property
	1, // 1: rpmpb.RPM.StoreProperty:input_type -> rpmpb.StorePropertyReq
	3, // 2: rpmpb.RPM.GetProperty:input_type -> rpmpb.GetPropertyReq
	5, // 3: rpmpb.RPM.RemoveProperty:input_type -> rpmpb.RemovePropertyReq
	7, // 4: rpmpb.RPM.ListProperties:input_type -> rpmpb.PropertyFilter
	2, // 5: rpmpb.RPM.StoreProperty:output_type -> rpmpb.StorePropertyRes
	4, // 6: rpmpb.RPM.GetProperty:output_type -> rpmpb.GetPropertyRes
	6, // 7: rpmpb.RPM.RemoveProperty:output_type -> rpmpb.RemovePropertyRes
	0, // 8: rpmpb.RPM.ListProperties:output_type -> rpmpb.Property
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpm_proto_init() }
func file_rpm_proto_init() {
	if File_rpm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Property); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StorePropertyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StorePropertyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPropertyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPropertyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemovePropertyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpm_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemovePropertyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpm_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PropertyFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpm_proto_goTypes,
		DependencyIndexes: file_rpm_proto_depIdxs,
		MessageInfos:      file_rpm_proto_msgTypes,
	}.Build()
	File_rpm_proto = out.File
	file_rpm_proto_rawDesc = nil
	file_rpm_proto_goTypes = nil
	file_rpm_proto_depIdxs = nil
}
